version: "3.3"
services:
  ydb:
    image: ydbplatform/local-ydb:latest
    restart: always
    ports:
      - 2136:2136
    hostname: localhost
    environment:
      - YDB_ENABLE_COLUMN_TABLES=true
      - YDB_USE_IN_MEMORY_PDISKS=true